name: Bug Report
description: bug report
title: "🐛 [bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 2.9.5
        - 2.9.4
        - 2.9.3
        - 2.9.2
        - 2.9.1
      default: 0
    validations:
      required: true
  - type: dropdown
    id: device_info 
    attributes:
      label: What device are you seeing the problem on?
      multiple: true
      options:
        - Samsung
        - Google Pixel
        - Xiaomi (HyperOS)
        - RedMagic
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: duplication
      description: By submitting this issue, you didn't saw any issues duplicate with this issue
      options:
        - label: I Agree
          required: true
