name: Build and Upload Release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag for the new version'
        required: true
        default: 'v2.9.3'
      release_notes:
        description: 'Release notes for the new version'
        required: true
        default: 'Initial release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download vectras-vm-arm64-v8a.tar.gz
        run: wget -O vectras-vm-arm64-v8a.tar.gz https://github.com/xoureldeen/Vectras-VM-Android/releases/download/v2.9.2/vectras-vm-arm64-v8a.tar.gz

      - name: Download vectras-vm-x86_64.tar.gz
        run: wget -O vectras-vm-x86_64.tar.gz https://github.com/xoureldeen/Vectras-VM-Android/releases/download/v2.9.2/vectras-vm-x86_64.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Ensure you have the PAT_TOKEN secret set
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: Release ${{ github.event.inputs.release_tag }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
  
      - name: Upload vectras-vm-arm64-v8a.tar.gz to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: vectras-vm-arm64-v8a.tar.gz
          asset_name: vectras-vm-arm64-v8a.tar.gz
          asset_content_type: application/gzip
  
      - name: Upload vectras-vm-x86_64.tar.gz to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: vectras-vm-x86_64.tar.gz
          asset_name: vectras-vm-x86_64.tar.gz
          asset_content_type: application/gzip

