name: Build and Upload Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Android app in release mode
        run: bash ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: Release ${{ github.event.inputs.release_tag }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-release-apk
          path: app/build/outputs/apk/release/app-release.apk  # Update this path if necessary

      - name: Download additional files
        run: |
          wget https://github.com/xoureldeen/Vectras-VM-Android/releases/download/${{ github.event.inputs.release_tag }}/vectras-vm-arm64-v8a.tar.gz
          wget https://github.com/xoureldeen/Vectras-VM-Android/releases/download/${{ github.event.inputs.release_tag }}/vectras-vm-x86_64.tar.gz

      - name: Upload additional files
        uses: actions/upload-artifact@v2
        with:
          name: vectras-vm-files
          path: |
            vectras-vm-arm64-v8a.tar.gz
            vectras-vm-x86_64.tar.gz
