name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: BuildAPK

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew







    - name: Build Universal Debug APK
      run: ./gradlew assembleDebug

    - name: Build Universal Release APK
      run: ./gradlew assembleRelease



    - name: Upload Universal Debug APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-universal-debug-apk
        path: app/build/outputs/apk/debug/app-universal-debug.apk

    - name: Upload Universal Release APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-universal-release-apk
        path: app/build/outputs/apk/release/app-universal-release-unsigned.apk

