name: Deprecated API Scan

on:
  push:
    branches: [ master, chore/** ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    name: scan (kotlin=${{ matrix.kotlin }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kotlin: [ false, true ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle Cache
        uses: gradle/actions/setup-gradle@v3
      - name: Run deprecatedApiScan
        run: |
          ./gradlew deprecatedApiScan -PskipFirmware -PjsonReport -PfailOnDeprecated ${{ matrix.kotlin && '-PscanKotlin' || '' }}
      - name: Upload JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deprecated-api-report-kotlin-${{ matrix.kotlin }}
          path: build/deprecated-api-report.json
