name: Fastlane

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  fastlane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install || gem install fastlane
      - name: Run Fastlane
        run: fastlane metadata
        