name: Firmware Check

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'app/build.gradle'
      - 'gradle/libs.versions.toml'
      - '.github/workflows/firmware-ci.yml'
      - 'README.md'
  workflow_dispatch:

jobs:
  firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Firmware Fetch + Verify
        env:
          QEMU_VARS_URL: ${{ secrets.QEMU_VARS_URL }}
          QEMU_VARS_SHA256: ${{ secrets.QEMU_VARS_SHA256 }}
          RELEASEX64_OVMF_VARS_URL: ${{ secrets.RELEASEX64_OVMF_VARS_URL }}
          RELEASEX64_OVMF_VARS_SHA256: ${{ secrets.RELEASEX64_OVMF_VARS_SHA256 }}
        run: ./gradlew :app:ciAllFirmwareCheck --no-daemon --stacktrace
      - name: Print Primary Firmware Hash
        run: ./gradlew :app:printFirmwareSha256 --no-daemon
