name: Release Drafter

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write        # to update release drafts
  pull-requests: write   # to read PR labels/titles for autolabeler

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Run Release Drafter (update draft only)
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}