name: Release Drafter

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write        # update release drafts
  pull-requests: read    # read PR labels/titles for autolabeler

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Verify config exists
        run: |
          test -f .github/release-drafter.yml || { echo 'Config missing'; exit 1; }
      - name: Run Release Drafter (update draft only)
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: .github/release-drafter.yml